<a href="https://colab.research.google.com/github/KIHOON71/pytorch_tutorial/blob/main/pytorch_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensor Initializing

- numpy array와 tensor의 차이점은 tensor는 gpu나 하드웨어 가속기에서 돌아갈 수 있다는 점이다.
- tensor는 또한 optimizing 할 때 자동 미분될 수 있다. 

In [ ]:
import torch
import numpy as np


In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [ ]:
x = torch.empty(size=(3,3))
print(x)
x1 = torch.zeros((3,3))
print(x1)
x2 = torch.rand((3,3))
print(x2)

x3 = torch.ones((3,3))
print(x3)

x4 = torch.eye(5,5) # identical tensor 반환
print(x4)

x5 = torch.arange(start=0, end=5, step=1)
print(x5)

x6 = torch.linspace(start=0.1, end=1, steps=10)
print(x6)

#normal_ 함수를 통해 평균과 편차를 조정하여 가우시안 분포를 만들어낼 수 있다
x7 = torch.empty(size=(1,5)).normal_(mean=0, std=1) 
print(x7)

#torch.rand와 비슷한 방식
x8 = torch.empty(size=(1,5)).uniform_(0, 1)
print(x8)

#torch.eye와 비슷하게 identical matrix를 생성 가능
x9 = torch.diag(torch.ones(3))
print(x9)

tensor([[-1.4707e-05,  3.0859e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0859e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8466, 0.0302, 0.9789],
        [0.4195, 0.1151, 0.0507],
        [0.0596, 0.9918, 0.2364]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.3913,  0.7070, -0.4190, -1.6684,  0.7815]])
tensor([[0.8116, 0.6493, 0.7149, 0.4630, 0.6862]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### Tensor Type Convert

In [ ]:
t = torch.arange(4)
print(t.bool()) # boolean 타입으로 변환
print(t.short())
print(t.long())
print(t.half())
print(t.float())
print(t.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


## Numpy to Tensor

In [ ]:
np_array = np.zeros((5,5))
t = torch.from_numpy(np_array)
print(t)
np_b = t.numpy()
print(np_b)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Tensor Operations

In [ ]:
#add
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

z1 = torch.empty(3)
torch.add(x,y, out=z1)
print(z1)

z2 = torch.add(x,y)
print(z2)

z = x + y
print(z)

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])


In [ ]:
#subtraction

z = x - y 
print(z)

#Division
z = torch.true_divide(x,y)
print(z) 

# inplace operation
t = torch.zeros(3)
t.add_(x)
print(t)

# Exponentiation
z = x.pow(2)
# z = x ** 2
print(z)

#simple comparison
z = x > 2
print(z)

#Matrix Multiplication

x1 = torch.rand((2,5))
x2 = torch. rand((5,3))
x3 = torch.mm(x1, x2)
#x3 = x1.mm(x2)
print(x1)
print(x2)
print(x3)

#Matrix exponentiation
matrix_exp = torch.rand(5,5)
print(matrix_exp)
print(matrix_exp.matrix_power(3))

#elementwise mul
z = x * y
print(x, y , '\n', z)

#dot product
z = torch.dot(x, y)
print(z)

#batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out = torch.bmm(tensor1, tensor2)
print(out.shape)

#example of Brodcatsting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
z = x1 - x2
z2 = x1 ** x2
print(z)
print(z2)

#other operation
sum_x =torch.sum(x, dim=0) # 어떤 축을 따라 sum을 할 것인지
print(sum_x)
values, indices = torch.max(x, dim=0) # 크기와 위치 반환
print(values, indices)
values, indices = torch.min(x, dim=0)
print(values, indices)
abs_x = torch.abs(x)
print(abs_x)
z = torch.argmax(x, dim=0) # 위치만 반환
print(z)
z = torch.eq(x,y) # 같은 위치의 원소들이 같은지 체크하고 같으면 그 위치에 True, 다르면 False 반환
print(z)

torch.sort(y, dim=0, descending=False)
print(y)

z = torch.clamp(x, max=10) # x의 모든 원소가 0보다 작거나 같은지 확인
print(z)

xx = torch.tensor([1,0,1,1], dtype=torch.bool)
z3 = torch.any(xx)
print(z3)
zz = torch.all(xx)
print(zz)





tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([1., 2., 3.])
tensor([1, 4, 9])
tensor([False, False,  True])
tensor([[0.3919, 0.0253, 0.2571, 0.1020, 0.6831],
        [0.0015, 0.3732, 0.1328, 0.7789, 0.1631]])
tensor([[0.5588, 0.4989, 0.3835],
        [0.3845, 0.7182, 0.7995],
        [0.8960, 0.9468, 0.4033],
        [0.1345, 0.9282, 0.5860],
        [0.2255, 0.9387, 0.1310]])
tensor([[0.6268, 1.1930, 0.4235],
        [0.4048, 1.2706, 0.8303]])
tensor([[0.5120, 0.1842, 0.3644, 0.4598, 0.7507],
        [0.9091, 0.8122, 0.2881, 0.7905, 0.5596],
        [0.4531, 0.8259, 0.6250, 0.1878, 0.8349],
        [0.3842, 0.1911, 0.8885, 0.4972, 0.9542],
        [0.1665, 0.4735, 0.6286, 0.1731, 0.7314]])
tensor([[2.5745, 3.0778, 3.2901, 2.1560, 4.4234],
        [4.0872, 4.5177, 5.2046, 3.5418, 7.0196],
        [3.7955, 4.1145, 4.3666, 3.2739, 6.0082],
        [3.4893, 4.1774, 4.2207, 2.8944, 5.7366],
        [2.8148, 3.1570, 3.2003, 2.3870, 4.4088]])
tensor([1, 2, 3]) tensor([9, 8, 7]

##Indexing of Tensor

In [ ]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0]) # x[0. :]
print(x[0].shape)

print(x[:, 0])
print(x[:,0].shape)

print(x[2, 0:10]) # 3번쨰 배치의 0번째부터 9까지의 인덱스의 feature들을 불러온다.

# fancy 인덱싱

x = torch.arange(10)
indices = [2,5,8]

print(x[indices])

x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x)
print(x[rows, cols])  # (1,4) 위치에 있는 값을 불러오고, (0,0) 위치에 있는 값을 불러온다.

#more advanced indexing

x = torch.arange(10)
print(x[(x < 2 ) | (x > 8)])
print(x[x.remainder(2) == 0]) # 2로 나웠을 때 0

#useful operation

print(torch.where(x > 5, x, x*2)) # 조건을 만족하면 x, 만족하지 못하면 x*2

print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension()) # numpy.ndarray.ndim과 같음
print(x.numel()) # 원소의 개수를 반환 해줌

tensor([0.1413, 0.0161, 0.0217, 0.2201, 0.7234, 0.9591, 0.1264, 0.0825, 0.6421,
        0.0628, 0.9447, 0.8266, 0.3253, 0.4549, 0.1325, 0.3835, 0.7343, 0.5748,
        0.8186, 0.3351, 0.1684, 0.3404, 0.8785, 0.0595, 0.5967])
torch.Size([25])
tensor([0.1413, 0.8301, 0.8789, 0.7912, 0.5873, 0.8515, 0.9949, 0.8133, 0.1507,
        0.3242])
torch.Size([10])
tensor([0.8789, 0.2368, 0.5881, 0.2384, 0.3285, 0.4095, 0.3870, 0.3793, 0.2484,
        0.9177])
tensor([2, 5, 8])
tensor([[0.7621, 0.3751, 0.1026, 0.0283, 0.2268],
        [0.5530, 0.1575, 0.2088, 0.8732, 0.1521],
        [0.1940, 0.5868, 0.5165, 0.0922, 0.3462]])
tensor([0.1521, 0.7621])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


## Tensor Reshaping

In [ ]:
x = torch.arange(9)

x_3x3 = x.view(3,3) # sometime dangerous, contiguous memory 방식

print(x_3x3)
x_3x3 = x.reshape(3,3) # safe, 값을 통째로 복사 하기 때문에 메모리적으로 손해
print(x_3x3)

# contiguous 
y = x_3x3.t()

#print(y.view(9)) # it will make an error
print(y.contiguous().view(9))


x1 = torch.rand((2,5))
x2 = torch.rand((2,5))

print(torch.cat((x1, x2), dim=1).shape)
print(torch.cat((x1, x2), dim=0).shape)


z = x1.view(-1) # flatten -1
print(z)

batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([2, 10])
torch.Size([4, 5])
tensor([0.9378, 0.0728, 0.3719, 0.4965, 0.2634, 0.0380, 0.6892, 0.0123, 0.8515,
        0.8424])
torch.Size([64, 10])
